# -*- coding: utf-8 -*-
"""Customer_Churn1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NiZLCaFx3IArazONqTP2f0GsLXxuSGlU

**DATA COLLECTION**

mengambil dataset dari kaggle https://www.kaggle.com/datasets/blastchar/telco-customer-churn/data

**LOAD DATA**
"""

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

df = pd.read_csv('dataset/raw/Telco-Customer-Churn.csv')
df.head()

"""**DATA UNDERSTANDING**"""

#kalo ini buat liat tipe data
df.info()

#buat cek data kosong yachh
df.isnull().sum()

df.duplicated().sum()

df.describe()

df.nunique()

#buat tau jumlah kategori tiap kolom

df['Churn'].value_counts()

"""**EXPLORATORY DATA ANALYSIS**"""

#countplot buat ngitung jumlah
sns.countplot(x='Churn', data=df)
plt.title('Jumlah Churn')
plt.show()

#insight sebagian besar pelanggan tidak churn, tetepai jg terdapat jumlah churn yg signifikan

#buat bandingin tiap jenis kolom
sns.countplot(x='Contract', hue='Churn', data=df)
plt.title('Jumlah Churn berdasarkan Contract')
plt.show()

#insightnya pelanggan yg cotractnya month to month lebih banyak churnya dibanding yg kontraknya
#jangka panjang. hal ini menunjukkan bahwa pelanggan tanpa kontrak yg panjang lebih mudah pindah layanan.

sns.boxplot(x='Churn', y='tenure', data=df)
plt.title('Tenure berdasarkan churn')
plt.show()

#insighntya adalah pelanggan yg churn itu malah punya tenure (pelanggan baru )yg lebih rendah drpd pelanggan yg tidak churn

sns.boxplot(x='Churn', y='MonthlyCharges', data=df)
plt.title('Monthly Charges berdasarkan churn')
plt.show()

#insighntya adlh pelanggan dg biaya bulanan lebih tinggi itu cenderung lebih bnayak churn

sns.countplot(x='PaymentMethod', hue='Churn', data=df)
plt.title('Jumlah Churn berdasarkan Payment Method')
plt.xticks(rotation=30)
plt.show()

"""**DATA PREPROCESSING**"""

#mendeteksi outlier
Q1 = df['tenure'].quantile(0.25)
Q3 = df['tenure'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outlier = df[(df['tenure'] < lower) | (df['tenure'] > upper)]
print("Jumlah outlier:", len(outlier))

#buat mengubah tipe data, karna sblmnya total biaya itu harusnya float bukan string, sehingga kita harus mengubahnya
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

df = df.dropna()

#menghapus kolom customer id karena tidak dibtuuhkan/ tidak berpengaruh thd churn
df = df.drop('customerID', axis=1)

#encoding
df = pd.get_dummies(df, drop_first=True)

#memisahkan fitur dan target
X = df.drop('Churn_Yes', axis=1)
y = df['Churn_Yes']

#memastikan target numerik
y = y.astype(int)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42)

#dta ini diabgi dulu jadi data training dan testing buat menghindari data leakage. teknik SMOTE
#diterapkan agar model tidak bias thd data uji.

#buat menyeimbangkan data bair mode ga bias ke mayoritas
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train, y_train = smote.fit_resample(X_train, y_train)

print("Sebelum SMOTE:")
print(y.value_counts())

print("Setelah SMOTE:")
print(pd.Series(y_train).value_counts())


import mlflow
import mlflow.sklearn

mlflow.set_tracking_uri("file:./mlruns")   # ⬅️ TAMBAHKAN DI SINI

mlflow.set_experiment("Churn Experiment")
mlflow.sklearn.autolog()


"""**MODELING**"""

model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

results = []

for depth in [3, 5, 7, 10, 15, 20]:
    for split in [2, 5, 10, 20]:
        for leaf in [1, 2, 4, 6]:
            for crit in ['gini', 'entropy']:
                for feature in ['sqrt', 'log2', None]:

                    with mlflow.start_run():

                        model = DecisionTreeClassifier(
                            max_depth=depth,
                            min_samples_split=split,
                            min_samples_leaf=leaf,
                            max_features=feature,
                            criterion=crit,
                            class_weight='balanced',
                            random_state=42
                        )

                        model.fit(X_train, y_train)

                        y_pred = model.predict(X_test)

                        acc = accuracy_score(y_test, y_pred)

                        report = classification_report(
                            y_test,
                            y_pred,
                            output_dict=True
                        )

                        precision = report['1']['precision']
                        recall = report['1']['recall']
                        f1 = report['1']['f1-score']

                        # LOG PARAMETER
                        mlflow.log_param("max_depth", depth)
                        mlflow.log_param("min_samples_split", split)
                        mlflow.log_param("min_samples_leaf", leaf)
                        mlflow.log_param("criterion", crit)
                        mlflow.log_param("max_features", feature)

                        # LOG METRIC
                        mlflow.log_metric("accuracy", acc)
                        mlflow.log_metric("precision_churn", precision)
                        mlflow.log_metric("recall_churn", recall)
                        mlflow.log_metric("f1_churn", f1)

                        results.append({
                            'max_depth': depth,
                            'min_samples_split': split,
                            'min_samples_leaf': leaf,
                            'criterion': crit,
                            'max_features': feature,
                            'accuracy': acc,
                            'recall_churn': recall,
                            'f1_churn': f1
                        })

df_results = pd.DataFrame(results)

print("\n=== HASIL EXPERIMENT ===\n")
print(df_results)

best = df_results.sort_values(by='recall_churn', ascending=False)
best_params = best.iloc[0]

print("\n=== PARAMETER TERBAIK ===\n")
print(best_params)

best_model = DecisionTreeClassifier(
    max_depth=int(best_params['max_depth']),
    min_samples_split=int(best_params['min_samples_split']),
    criterion=best_params['criterion'],
    class_weight='balanced',
    random_state=42
)

best_model.fit(X_train, y_train)

y_pred = best_model.predict(X_test)

print("\n=== HASIL MODEL FINAL ===\n")
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

"""**LOG EXPERIMENT**
untuk mencatat hasil percobaan model terbaik
"""

# pakai hasil dari best_model (bukan typo)
report = classification_report(y_test, y_pred, output_dict=True)

# hitung ulang accuracy biar sesuai model terbaik
acc_final = accuracy_score(y_test, y_pred)

log = pd.DataFrame({
    'Model': ['Decision Tree'],
    'Accuracy': [acc_final],
    'Precision (Churn)': [report['1']['precision']],
    'Recall (Churn)': [report['1']['recall']],
    'F1-score (Churn)': [report['1']['f1-score']]
})

print("\n=== LOG EXPERIMENT FINAL ===\n")
print(log)

import joblib

joblib.dump(best_model, 'best_model.pkl')

print("\nModel berhasil disimpan sebagai best_model.pkl")


